"""add_scoring_jobs

Revision ID: 4f30f90ba86e
Revises: 42bccdaceb52
Create Date: 2026-04-17 19:46:10.426443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_scoring_jobs

Revision ID: 4f30f90ba86e
Revises: 42bccdaceb52
Create Date: 2026-04-17 19:46:10.426443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f30f90ba86e'
down_revision: Union[str, Sequence[str], None] = '42bccdaceb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create Enum type manually for PostgreSQL
    scoring_status_enum = sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='scoringstatus')
    scoring_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoring_jobs', sa.Column('id', sa.UUID(), nullable=True))
    # Fill id with new UUIDs if there are existing rows
    op.execute("UPDATE scoring_jobs SET id = gen_random_uuid() WHERE id IS NULL")
    op.alter_column('scoring_jobs', 'id', nullable=False)

    op.add_column('scoring_jobs', sa.Column('error_message', sa.String(length=2048), nullable=True))
    
    # Cast VARCHAR to Enum
    op.execute("ALTER TABLE scoring_jobs ALTER COLUMN status TYPE scoringstatus USING status::scoringstatus")
    
    op.drop_index('ix_scoring_jobs_status', table_name='scoring_jobs')
    op.drop_index('ix_scoring_jobs_upload_id', table_name='scoring_jobs')
    
    # Update Primary Key
    op.drop_constraint('scoring_jobs_pkey', 'scoring_jobs', type_='primary')
    op.create_primary_key('scoring_jobs_pkey', 'scoring_jobs', ['id'])

    op.drop_column('scoring_jobs', 'job_id')
    op.drop_column('scoring_jobs', 'error')
    op.alter_column('transactions', 'dep_station',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('transactions', 'arr_station',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'arr_station',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'dep_station',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    
    op.add_column('scoring_jobs', sa.Column('job_id', sa.VARCHAR(length=36), nullable=True))
    op.execute("UPDATE scoring_jobs SET job_id = CAST(id AS VARCHAR(36))")
    op.alter_column('scoring_jobs', 'job_id', nullable=False)

    op.add_column('scoring_jobs', sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
    
    op.drop_constraint('scoring_jobs_pkey', 'scoring_jobs', type_='primary')
    op.create_primary_key('scoring_jobs_pkey', 'scoring_jobs', ['job_id'])

    op.create_index('ix_scoring_jobs_upload_id', 'scoring_jobs', ['upload_id'], unique=False)
    op.create_index('ix_scoring_jobs_status', 'scoring_jobs', ['status'], unique=False)

    # Cast back to VARCHAR
    op.execute("ALTER TABLE scoring_jobs ALTER COLUMN status TYPE VARCHAR(20) USING status::VARCHAR(20)")

    op.drop_column('scoring_jobs', 'error_message')
    op.drop_column('scoring_jobs', 'id')
    
    # Drop Enum type
    sa.Enum(name='scoringstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
