"""add_is_manual_to_passenger_scores

Revision ID: 7cef62923e64
Revises: bff0cf4461fb
Create Date: 2026-04-18 10:37:19.905705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cef62923e64'
down_revision: Union[str, Sequence[str], None] = 'bff0cf4461fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passenger_scores', sa.Column('is_manual', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_passenger_scores_is_manual'), 'passenger_scores', ['is_manual'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passenger_scores_is_manual'), table_name='passenger_scores')
    op.drop_column('passenger_scores', 'is_manual')
    # ### end Alembic commands ###
