"""initial

Revision ID: b01767d7336b
Revises: 
Create Date: 2026-04-14 13:55:56.219617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.infrastructure.db.models.types.entities
import app.infrastructure.db.models.types.user


# revision identifiers, used by Alembic.
revision: str = 'b01767d7336b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers',
    sa.Column('id', app.infrastructure.db.models.types.entities.PassengerIdType(), nullable=False),
    sa.Column('fio_clean', sa.String(length=255), nullable=False),
    sa.Column('fake_fio_score', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('features', app.infrastructure.db.models.types.entities.PassengerFeaturesType(), nullable=True),
    sa.Column('score', app.infrastructure.db.models.types.entities.PassengerScoreType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_fio_clean'), 'passengers', ['fio_clean'], unique=False)
    op.create_index(op.f('ix_passengers_last_seen_at'), 'passengers', ['last_seen_at'], unique=False)
    op.create_table('risk_concentrations',
    sa.Column('id', app.infrastructure.db.models.types.entities.RiskConcentrationIdType(), nullable=False),
    sa.Column('dimension_type', sa.Enum('CHANNEL', 'AGGREGATOR', 'TERMINAL', 'CASHDESK', 'POINT_OF_SALE', name='dimensiontype'), nullable=False),
    sa.Column('dimension_value', sa.String(length=255), nullable=False),
    sa.Column('total_ops', sa.Integer(), nullable=False),
    sa.Column('highrisk_ops', sa.Integer(), nullable=False),
    sa.Column('share_highrisk_ops', sa.Float(), nullable=False),
    sa.Column('lift_vs_base', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_concentrations_calculated_at'), 'risk_concentrations', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_risk_concentrations_dimension_type'), 'risk_concentrations', ['dimension_type'], unique=False)
    op.create_index(op.f('ix_risk_concentrations_dimension_value'), 'risk_concentrations', ['dimension_value'], unique=False)
    op.create_table('transactions',
    sa.Column('id', app.infrastructure.db.models.types.entities.TransactionIdType(), nullable=False),
    sa.Column('upload_id', app.infrastructure.db.models.types.entities.UploadIdType(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('op_type', sa.Enum('SALE', 'REFUND', name='operationtype'), nullable=False),
    sa.Column('op_datetime', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('dep_datetime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('train_no', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('aggregator', sa.String(length=100), nullable=True),
    sa.Column('terminal', sa.String(length=100), nullable=True),
    sa.Column('cashdesk', sa.String(length=100), nullable=True),
    sa.Column('point_of_sale', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=True),
    sa.Column('iin', sa.String(length=20), nullable=True),
    sa.Column('doc_no', sa.String(length=50), nullable=True),
    sa.Column('passenger_id', app.infrastructure.db.models.types.entities.PassengerIdType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_aggregator'), 'transactions', ['aggregator'], unique=False)
    op.create_index(op.f('ix_transactions_cashdesk'), 'transactions', ['cashdesk'], unique=False)
    op.create_index(op.f('ix_transactions_channel'), 'transactions', ['channel'], unique=False)
    op.create_index(op.f('ix_transactions_iin'), 'transactions', ['iin'], unique=False)
    op.create_index(op.f('ix_transactions_op_datetime'), 'transactions', ['op_datetime'], unique=False)
    op.create_index(op.f('ix_transactions_op_type'), 'transactions', ['op_type'], unique=False)
    op.create_index(op.f('ix_transactions_passenger_id'), 'transactions', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_transactions_point_of_sale'), 'transactions', ['point_of_sale'], unique=False)
    op.create_index(op.f('ix_transactions_terminal'), 'transactions', ['terminal'], unique=False)
    op.create_index(op.f('ix_transactions_upload_id'), 'transactions', ['upload_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', app.infrastructure.db.models.types.entities.UploadIdType(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=1024), nullable=False),
    sa.Column('uploaded_by_user_id', app.infrastructure.db.models.types.entities.UserIdType(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='uploadstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.infrastructure.db.models.types.user.UserIdType(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', app.infrastructure.db.models.types.user.EmailType(length=320), nullable=False),
    sa.Column('role', sa.Enum('ANALYST', 'SECURITY', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('password_hash', app.infrastructure.db.models.types.user.PasswordHashType(length=1024), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refresh_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', app.infrastructure.db.models.types.user.UserIdType(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_table('users')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_transactions_upload_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_terminal'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_point_of_sale'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_passenger_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_op_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_op_datetime'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_iin'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_channel'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_cashdesk'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_aggregator'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_risk_concentrations_dimension_value'), table_name='risk_concentrations')
    op.drop_index(op.f('ix_risk_concentrations_dimension_type'), table_name='risk_concentrations')
    op.drop_index(op.f('ix_risk_concentrations_calculated_at'), table_name='risk_concentrations')
    op.drop_table('risk_concentrations')
    op.drop_index(op.f('ix_passengers_last_seen_at'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_fio_clean'), table_name='passengers')
    op.drop_table('passengers')
    # ### end Alembic commands ###
