"""add_route_field

Revision ID: bff0cf4461fb
Revises: 4f30f90ba86e
Create Date: 2026-04-18 08:56:59.917636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff0cf4461fb'
down_revision: Union[str, Sequence[str], None] = '4f30f90ba86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('route', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'route')
    # ### end Alembic commands ###
